name: Pull Request CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Yarn Install
      uses: sergioramos/yarn-actions/install@master
      with:
        frozen-lockfile: true

    - name: Run AVA Tests
      uses: sergioramos/yarn-actions/run@master
      with:
        script: test

    - name: Run Eslint Checks 
      uses: sergioramos/yarn-actions/run@master
      with:
        script: lint
